//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Runner
    {
        public Runner()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int ID { get; set; }
        public string HorseName { get; set; }
        public int Number { get; set; }
        public int Barrier { get; set; }
        public int RaceID { get; set; }
        public decimal Weight { get; set; }
        public int HorseID { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual Horse Horse { get; set; }
    }
}
