//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.Races = new HashSet<Race>();
        }
    
        public int ID { get; set; }

        public string Name { get; set; }
    
        public virtual ICollection<Race> Races { get; set; }
    }
}
